// Generated by https://quicktype.io

export interface DalleTypes {
    created:   number;
    data:      Datum[];
    prompt:    string;
    _id:       string;
    creator:   string;
    createdAt: string;
    updatedAt: string;
}

export interface Datum {
    url: string;
}

export interface imagesGenerated {
    url:string;
}



// Generated by https://quicktype.io

export interface Dalle2Types {
    dataTemp:       any[];
    _id:            string;
    created:        number;
    data:           Datum[];
    prompt:         string;
    creator:        string;
    cloudinarySave: CloudinarySave;
    createdAt:      string;
    updatedAt:      string;
    __v:            number;
}

export interface CloudinarySave {
    url:       string;
    public_id: string;
}

export interface Datum {
    url: string;
}

