// Generated by https://quicktype.io

export interface VoicesTypes {
  architecture: Architecture;
  category: string;
  contributors: string[];
  controls: boolean;
  display_name: string;
  is_active: boolean;
  model_id: string;
  memberships: Membership[];
  is_private: boolean;
  is_primary: boolean;
  name: string;
  symbol_set: SymbolSet;
  voicemodel_uuid: string;
  hifi_gan_vocoder: string;
  ml_model_id: number;
  speaker_id: number | null;
  language: Language;
}

export enum Architecture {
  Fastpitch = "fastpitch",
  Tacotron2 = "tacotron2",
  Talknet = "talknet",
}

export enum Language {
  Dutch = "dutch",
  English = "english",
  Polish = "polish",
  Portuguese = "portuguese",
  Spanish = "spanish",
}

export interface Membership {
  name: Name;
  id: number;
}

export enum Name {
  Studio = "studio",
}

export enum SymbolSet {
  NvidiaTaco2 = "nvidia_taco2",
}

export interface datos {
  texToSpeech?: string;
  voicesSelected: string;
  ttsField: string;
  pace?: number;
  pitch?: number;
  duration?: number;
  name?:string;
}

export interface responseVoices {
  failed_at: string | null;
  finished_at: string;
  meta: string | null;
  path: string | undefined;
  started_at: string | null;
  tss: string;
}

export interface VoicesTypesResponse {
  failed_at:        string | null;
  finished_at:      string | null;
  meta:             string | null;
  path:             string | null;
  started_at:       string | null;
  uuid:             string | null;
  tts:              string | null;
}

